### ISSUE TITLE
Robustness against URLs that need redirect

### ISSUE THREAD

**Issue by jmauersberger** [JamaSoftware/RestClient#11]
If I use a server base URL like GET: https://kpit.jamacloud.com/blafoobar/rest/v1/, the JamaClient.ping() method succeeds, because its actually only checks for errors (ApacheHttpClient:#120). However, in this case a 302 (redirect) is returned and all subsequent calls to the API fail with an exception:

`java.lang.NullPointerException
	at java.io.StringReader.<init>(StringReader.java:50)
	at org.json.simple.parser.JSONParser.parse(JSONParser.java:79)
	at org.json.simple.parser.JSONParser.parse(JSONParser.java:75)
	at com.jamasoftware.services.restclient.json.SimpleJsonUtil.parseObject(SimpleJsonUtil.java:133)`

Any idea how to make this more robust? Maybe the ping() evaluates the redirect and saves the redirected base URL? Or the client handles redirect calls on *any* get/put request (might be expensive).

**Comment by jmauersberger** [comment]
Maybe a related issues but maybe not. In a separate test environment the authentication procedure against a certain Jama server URL doe snot seems to work. Lets assume the URL is 

`https://IP:8443/contour/`

for that URL the login and initial ping call fails with

![grafik](https://cloud.githubusercontent.com/assets/23167084/25132972/9774794a-244b-11e7-8466-d58fa02246db.png)

However, for 

`https://IP:8443/contour/perspective.req`

he initial ping call works fine but any later call fails miserably.  Using the URL `https://IP/contour/rest/v1/` in the browser returns:

![grafik](https://cloud.githubusercontent.com/assets/23167084/25132909/6953d542-244b-11e7-99da-154eed0f1250.png)

in a 2.1.5.5 environment but also updating to 18 seems to have he same issue.
